import type { Campaign, ContentPackage, SmartSource } from "./index";

export const DEMO_SMART_SOURCES: readonly SmartSource[] = Object.freeze([
  {
    id: "src_product_launches",
    workspaceId: "ws_demo",
    name: "Product launches",
    provider: "google_drive",
    locations: [{ providerLocationId: "drive-folder-1", displayPath: "/Marketing/Product launches" }],
    recursive: true,
    readinessMode: "related_files",
    stabilizationWindowSeconds: 120,
    relatedFileMinimum: 2,
    allowedMimeTypes: ["image/*", "video/*", "application/pdf"],
    ignorePatterns: ["**/drafts/**", "~$*"],
    contextPackIds: ["ctx_brand", "ctx_products"],
    autonomyMode: "approval_required",
    enabled: true,
    lastScanAt: "2026-08-05T19:51:00.000Z",
  },
  {
    id: "src_research",
    workspaceId: "ws_demo",
    name: "Research & insights",
    provider: "sharepoint",
    locations: [{ providerLocationId: "sharepoint-folder-7", displayPath: "/Research/Approved" }],
    recursive: false,
    readinessMode: "ready_marker",
    stabilizationWindowSeconds: 300,
    readyMarker: "APPROVED",
    allowedMimeTypes: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    ignorePatterns: [],
    contextPackIds: ["ctx_brand", "ctx_research_policy"],
    autonomyMode: "approve_uncertain",
    enabled: true,
    lastScanAt: "2026-08-05T19:48:00.000Z",
  },
  {
    id: "src_events",
    workspaceId: "ws_demo",
    name: "Events & workshops",
    provider: "onedrive",
    locations: [{ providerLocationId: "onedrive-folder-3", displayPath: "/Events/Upcoming" }],
    recursive: true,
    readinessMode: "ai_recommended",
    stabilizationWindowSeconds: 180,
    aiConfidenceThreshold: 0.88,
    allowedMimeTypes: ["image/*", "text/calendar", "application/pdf"],
    ignorePatterns: ["**/archive/**"],
    contextPackIds: ["ctx_brand", "ctx_events"],
    autonomyMode: "confidence_based",
    enabled: true,
    lastScanAt: "2026-08-05T19:44:00.000Z",
  },
]);

export const DEMO_CONTENT_PACKAGES: readonly ContentPackage[] = Object.freeze([
  {
    id: "pkg_summer_release",
    workspaceId: "ws_demo",
    smartSourceId: "src_product_launches",
    title: "Summer collection release",
    status: "needs_review",
    assets: [],
    evidence: [],
    confidence: 0.92,
    createdAt: "2026-08-05T18:30:00.000Z",
    updatedAt: "2026-08-05T19:35:00.000Z",
  },
  {
    id: "pkg_quarterly_report",
    workspaceId: "ws_demo",
    smartSourceId: "src_research",
    title: "Quarterly impact report",
    status: "ready",
    assets: [],
    evidence: [],
    confidence: 0.97,
    createdAt: "2026-08-05T16:20:00.000Z",
    updatedAt: "2026-08-05T18:58:00.000Z",
  },
  {
    id: "pkg_workshop",
    workspaceId: "ws_demo",
    smartSourceId: "src_events",
    title: "Community workshop series",
    status: "analyzing",
    assets: [],
    evidence: [],
    createdAt: "2026-08-05T19:10:00.000Z",
    updatedAt: "2026-08-05T19:49:00.000Z",
  },
]);

export const DEMO_CAMPAIGNS: readonly Campaign[] = Object.freeze([
  {
    id: "cmp_summer",
    workspaceId: "ws_demo",
    name: "Summer launch",
    status: "active",
    contentPackageIds: ["pkg_summer_release"],
    steps: [],
    informationDepth: "contextual",
    promotionalStrength: "standard",
    autonomyMode: "approval_required",
  },
  {
    id: "cmp_impact",
    workspaceId: "ws_demo",
    name: "Impact report distribution",
    status: "active",
    contentPackageIds: ["pkg_quarterly_report"],
    steps: [],
    informationDepth: "detailed",
    promotionalStrength: "light",
    autonomyMode: "approve_uncertain",
  },
]);
