"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { StoredCampaignInstance } from "@market-me/database";

export function CampaignInstanceActions({ workspaceId, instance }: { workspaceId: string; instance: StoredCampaignInstance }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [outputs, setOutputs] = useState<Record<string, string>>({});
  async function post(url: string, body: Record<string, unknown>) { setPending(true); setError(""); const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); setPending(false); if (!response.ok) setError(payload?.error?.message ?? "Workflow command failed."); router.refresh(); }
  return <div className="review-actions"><div><span>Workflow controls</span>{instance.status === "paused" ? <button className="button-primary" disabled={pending} onClick={() => post(`/api/v1/campaign-instances/${instance.id}/commands`, { workspaceId, command: "resume" })}>Resume</button> : <button className="button-secondary" disabled={pending || !["active", "scheduled"].includes(instance.status)} onClick={() => post(`/api/v1/campaign-instances/${instance.id}/commands`, { workspaceId, command: "pause" })}>Pause</button>}<button className="button-secondary" disabled={pending || ["completed", "failed", "canceled"].includes(instance.status)} onClick={() => post(`/api/v1/campaign-instances/${instance.id}/commands`, { workspaceId, command: "cancel" })}>Cancel</button></div>{instance.stepRuns.filter((run) => run.status === "manual_resolution" && run.stepKey).map((run) => <div key={run.id}><span>Complete {run.stepName ?? run.stepKey}</span><input value={outputs[run.id] ?? "{}"} onChange={(event) => setOutputs((current) => ({ ...current, [run.id]: event.target.value }))} /><button className="button-primary" disabled={pending} onClick={() => { try { const output = JSON.parse(outputs[run.id] ?? "{}"); post(`/api/v1/campaign-instances/${instance.id}/steps/${run.stepKey}/complete`, { workspaceId, output }); } catch { setError("Manual step output must be valid JSON."); } }}>Record completion</button></div>)}{error && <p className="form-error">{error}</p>}</div>;
}
