"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { StoredAudienceProfile, StoredBrandProfile } from "@market-me/database";

const lines = (value: readonly string[] | undefined) => value?.join("\n") ?? "";
const split = (value: string) => value.split(/\r?\n|,/).map((entry) => entry.trim()).filter(Boolean);
const pairs = (value: string) => Object.fromEntries(value.split(/\r?\n/).map((entry) => entry.split(":")).filter((parts) => parts.length > 1).map(([key, ...rest]) => [key.trim(), rest.join(":").trim()]).filter(([key]) => key));
const unpairs = (value: Readonly<Record<string, string>> | undefined) => Object.entries(value ?? {}).map(([key, entry]) => `${key}: ${entry}`).join("\n");

const controlInitial = (version: { informationDepthDefault?: string; informationDepthCeiling?: string; promotionalStrengthDefault?: string; promotionalStrengthCeiling?: string } | undefined) => ({
  informationDepthDefault: version?.informationDepthDefault ?? "", informationDepthCeiling: version?.informationDepthCeiling ?? "",
  promotionalStrengthDefault: version?.promotionalStrengthDefault ?? "", promotionalStrengthCeiling: version?.promotionalStrengthCeiling ?? "",
});

function Controls({ values, set }: { values: Record<string, unknown>; set: (key: string, value: string) => void }) {
  return <section className="form-section"><div><h2>Communication controls</h2><p>Defaults guide campaigns. Ceilings are hard guardrails; campaign values above them are rejected.</p></div><div className="field-grid">
    <Select label="Information depth default" value={String(values.informationDepthDefault)} onChange={(value) => set("informationDepthDefault", value)} options={["", "minimal", "teaser", "contextual", "detailed", "comprehensive", "custom"]} />
    <Select label="Information depth ceiling" value={String(values.informationDepthCeiling)} onChange={(value) => set("informationDepthCeiling", value)} options={["", "minimal", "teaser", "contextual", "detailed", "comprehensive"]} />
    <Select label="Promotional strength default" value={String(values.promotionalStrengthDefault)} onChange={(value) => set("promotionalStrengthDefault", value)} options={["", "informational", "subtle", "light", "standard", "strong", "campaign_push", "custom"]} />
    <Select label="Promotional strength ceiling" value={String(values.promotionalStrengthCeiling)} onChange={(value) => set("promotionalStrengthCeiling", value)} options={["", "informational", "subtle", "light", "standard", "strong", "campaign_push"]} />
  </div></section>;
}

export function BrandProfileForm({ workspaceId, profile }: { workspaceId: string; profile?: StoredBrandProfile }) {
  const version = profile?.draftVersion ?? profile?.currentVersion; const data = version?.profile;
  const [values, setValues] = useState<Record<string, unknown>>({ name: profile?.name ?? "", description: profile?.description ?? "", officialName: data?.officialName ?? "", shortName: data?.shortName ?? "", profileDescription: data?.description ?? "", products: lines(data?.products), services: lines(data?.services), valuePropositions: lines(data?.valuePropositions), tones: lines(data?.voice.tones), formality: data?.voice.formality ?? "", humor: data?.voice.humor ?? "", emotion: data?.voice.emotion ?? "", preferredTerms: lines(data?.terminology.preferred), prohibitedTerms: lines(data?.terminology.prohibited), capitalization: data?.style.capitalization ?? "", punctuation: data?.style.punctuation ?? "", emoji: data?.style.emoji ?? "", hashtags: data?.style.hashtags ?? "", abbreviations: data?.style.abbreviations ?? "", callToActionGuidance: data?.callToActionGuidance ?? "", claims: lines(data?.claims), evidenceRequirements: lines(data?.evidenceRequirements), requiredDisclosures: lines(data?.requiredDisclosures), attributionRules: lines(data?.attributionRules), competitorRules: lines(data?.competitorRules), visualGuidance: data?.visualGuidance ?? "", channelPersonas: unpairs(data?.channelPersonas), ...controlInitial(version) });
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const body = () => ({ workspaceId, name: values.name, description: values.description, profile: { officialName: values.officialName, shortName: optional(values.shortName), description: values.profileDescription, products: split(String(values.products)), services: split(String(values.services)), valuePropositions: split(String(values.valuePropositions)), voice: { tones: split(String(values.tones)), formality: optional(values.formality), humor: optional(values.humor), emotion: optional(values.emotion) }, terminology: { preferred: split(String(values.preferredTerms)), prohibited: split(String(values.prohibitedTerms)) }, style: { capitalization: optional(values.capitalization), punctuation: optional(values.punctuation), emoji: optional(values.emoji), hashtags: optional(values.hashtags), abbreviations: optional(values.abbreviations) }, callToActionGuidance: optional(values.callToActionGuidance), claims: split(String(values.claims)), evidenceRequirements: split(String(values.evidenceRequirements)), requiredDisclosures: split(String(values.requiredDisclosures)), attributionRules: split(String(values.attributionRules)), competitorRules: split(String(values.competitorRules)), visualGuidance: optional(values.visualGuidance), channelPersonas: pairs(String(values.channelPersonas)) }, ...controlBody(values) });
  return <ProfileFormShell kind="brand" workspaceId={workspaceId} profileId={profile?.id} values={values} set={set} body={body}>
    <section className="form-section"><div><h2>Identity and offer</h2><p>Record the official identity and the approved value that content may communicate.</p></div><div className="field-grid"><Input label="Profile name" value={String(values.name)} set={(v) => set("name", v)} required /><Input label="Official brand name" value={String(values.officialName)} set={(v) => set("officialName", v)} required /><Input label="Short name" value={String(values.shortName)} set={(v) => set("shortName", v)} /><Text label="Internal description" value={String(values.description)} set={(v) => set("description", v)} /><Text label="Public brand description" value={String(values.profileDescription)} set={(v) => set("profileDescription", v)} /><Text label="Products (one per line)" value={String(values.products)} set={(v) => set("products", v)} /><Text label="Services (one per line)" value={String(values.services)} set={(v) => set("services", v)} /><Text label="Value propositions (one per line)" value={String(values.valuePropositions)} set={(v) => set("valuePropositions", v)} /></div></section>
    <section className="form-section"><div><h2>Voice and style</h2><p>These instructions change presentation, never the underlying approved facts.</p></div><div className="field-grid"><Text label="Tones" value={String(values.tones)} set={(v) => set("tones", v)} /><Input label="Formality" value={String(values.formality)} set={(v) => set("formality", v)} /><Input label="Humor" value={String(values.humor)} set={(v) => set("humor", v)} /><Input label="Emotion" value={String(values.emotion)} set={(v) => set("emotion", v)} /><Text label="Preferred terminology" value={String(values.preferredTerms)} set={(v) => set("preferredTerms", v)} /><Text label="Prohibited terminology" value={String(values.prohibitedTerms)} set={(v) => set("prohibitedTerms", v)} /><Input label="Capitalization" value={String(values.capitalization)} set={(v) => set("capitalization", v)} /><Input label="Punctuation" value={String(values.punctuation)} set={(v) => set("punctuation", v)} /><Input label="Emoji" value={String(values.emoji)} set={(v) => set("emoji", v)} /><Input label="Hashtags" value={String(values.hashtags)} set={(v) => set("hashtags", v)} /><Input label="Abbreviations" value={String(values.abbreviations)} set={(v) => set("abbreviations", v)} /><Text label="Channel personas (channel: guidance)" value={String(values.channelPersonas)} set={(v) => set("channelPersonas", v)} /></div></section>
    <section className="form-section"><div><h2>Claims and governance</h2><p>Capture evidence, disclosure, attribution, competitor, visual, and call-to-action constraints.</p></div><div className="field-grid"><Text label="Call-to-action guidance" value={String(values.callToActionGuidance)} set={(v) => set("callToActionGuidance", v)} /><Text label="Allowed claims" value={String(values.claims)} set={(v) => set("claims", v)} /><Text label="Evidence requirements" value={String(values.evidenceRequirements)} set={(v) => set("evidenceRequirements", v)} /><Text label="Required disclosures" value={String(values.requiredDisclosures)} set={(v) => set("requiredDisclosures", v)} /><Text label="Attribution rules" value={String(values.attributionRules)} set={(v) => set("attributionRules", v)} /><Text label="Competitor rules" value={String(values.competitorRules)} set={(v) => set("competitorRules", v)} /><Text label="Visual guidance" value={String(values.visualGuidance)} set={(v) => set("visualGuidance", v)} /></div></section>
    <Controls values={values} set={set} />
  </ProfileFormShell>;
}

export function AudienceProfileForm({ workspaceId, profile }: { workspaceId: string; profile?: StoredAudienceProfile }) {
  const version = profile?.draftVersion ?? profile?.currentVersion; const data = version?.profile;
  const [values, setValues] = useState<Record<string, unknown>>({ name: profile?.name ?? "", description: profile?.description ?? "", audienceType: version?.audienceType ?? "consumer", purpose: data?.purpose ?? "", industries: lines(data?.industries), roles: lines(data?.roles), interests: lines(data?.interests), locations: lines(data?.locations), languages: lines(data?.languages), knowledgeLevel: data?.knowledgeLevel ?? "", needs: lines(data?.needs), motivations: lines(data?.motivations), objections: lines(data?.objections), questions: lines(data?.questions), preferredChannels: lines(data?.preferredChannels), preferredFormats: lines(data?.preferredFormats), relationshipStage: data?.relationshipStage ?? "", familiarity: data?.familiarity ?? "", exclusions: lines(data?.exclusions), ...controlInitial(version) });
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const body = () => ({ workspaceId, name: values.name, description: values.description, audienceType: values.audienceType, profile: { purpose: values.purpose, industries: split(String(values.industries)), roles: split(String(values.roles)), interests: split(String(values.interests)), locations: split(String(values.locations)), languages: split(String(values.languages)), knowledgeLevel: optional(values.knowledgeLevel), needs: split(String(values.needs)), motivations: split(String(values.motivations)), objections: split(String(values.objections)), questions: split(String(values.questions)), preferredChannels: split(String(values.preferredChannels)), preferredFormats: split(String(values.preferredFormats)), relationshipStage: optional(values.relationshipStage), familiarity: optional(values.familiarity), exclusions: split(String(values.exclusions)) }, ...controlBody(values) });
  return <ProfileFormShell kind="audience" workspaceId={workspaceId} profileId={profile?.id} values={values} set={set} body={body}>
    <section className="form-section"><div><h2>Audience definition</h2><p>Describe an intended group without inferring sensitive traits about any individual.</p></div><div className="field-grid"><Input label="Profile name" value={String(values.name)} set={(v) => set("name", v)} required /><Select label="Audience type" value={String(values.audienceType)} onChange={(v) => set("audienceType", v)} options={["consumer", "business", "professional", "community", "media", "donor", "applicant", "partner", "mixed"]} /><Text label="Internal description" value={String(values.description)} set={(v) => set("description", v)} /><Text label="Purpose" value={String(values.purpose)} set={(v) => set("purpose", v)} required /><Text label="Industries" value={String(values.industries)} set={(v) => set("industries", v)} /><Text label="Roles" value={String(values.roles)} set={(v) => set("roles", v)} /><Text label="Interests" value={String(values.interests)} set={(v) => set("interests", v)} /><Text label="Locations" value={String(values.locations)} set={(v) => set("locations", v)} /><Text label="Languages" value={String(values.languages)} set={(v) => set("languages", v)} /><Input label="Knowledge level" value={String(values.knowledgeLevel)} set={(v) => set("knowledgeLevel", v)} /></div></section>
    <section className="form-section"><div><h2>Needs and engagement</h2><p>Guide useful presentation, objections, questions, channels, formats, and relationship stage.</p></div><div className="field-grid"><Text label="Needs" value={String(values.needs)} set={(v) => set("needs", v)} /><Text label="Motivations" value={String(values.motivations)} set={(v) => set("motivations", v)} /><Text label="Objections" value={String(values.objections)} set={(v) => set("objections", v)} /><Text label="Questions" value={String(values.questions)} set={(v) => set("questions", v)} /><Text label="Preferred channels" value={String(values.preferredChannels)} set={(v) => set("preferredChannels", v)} /><Text label="Preferred formats" value={String(values.preferredFormats)} set={(v) => set("preferredFormats", v)} /><Input label="Relationship stage" value={String(values.relationshipStage)} set={(v) => set("relationshipStage", v)} /><Input label="Familiarity" value={String(values.familiarity)} set={(v) => set("familiarity", v)} /><Text label="Exclusions" value={String(values.exclusions)} set={(v) => set("exclusions", v)} /></div></section>
    <Controls values={values} set={set} />
  </ProfileFormShell>;
}

function ProfileFormShell({ kind, workspaceId, profileId, children, body }: { kind: "brand" | "audience"; workspaceId: string; profileId?: string; values: Record<string, unknown>; set: (key: string, value: string) => void; body: () => unknown; children: React.ReactNode }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const base = kind === "brand" ? "brand-profiles" : "audience-profiles";
  async function save(event?: React.FormEvent) { event?.preventDefault(); setPending(true); setError(""); setMessage(""); const response = await fetch(profileId ? `/api/v1/${base}/${profileId}` : `/api/v1/${base}`, { method: profileId ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body()) }); const payload = await response.json().catch(() => ({})); setPending(false); if (!response.ok) { setError(payload?.error?.message ?? "Could not save the profile."); return false; } if (!profileId) router.push(`/audience/${kind}s/${payload.data.id}/edit`); setMessage("Profile draft saved."); router.refresh(); return true; }
  async function publish() { if (!profileId || !(await save())) return; setPending(true); const response = await fetch(`/api/v1/${base}/${profileId}/publish`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ workspaceId }) }); const payload = await response.json().catch(() => ({})); setPending(false); if (!response.ok) setError(payload?.error?.message ?? "Could not publish the profile."); else setMessage(`Published version ${payload.data.currentVersion.versionNumber}.`); router.refresh(); }
  return <form className="resource-form" onSubmit={save}>{children}<div className="form-actions"><button className="button-secondary" disabled={pending}>{pending ? "Saving..." : "Save draft"}</button>{profileId && <button className="button-primary" type="button" disabled={pending} onClick={publish}>Publish version</button>}{message && <p className="form-success form-message">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}</div></form>;
}

function optional(value: unknown) { const text = String(value ?? "").trim(); return text || undefined; }
function controlBody(values: Record<string, unknown>) { return { informationDepthDefault: optional(values.informationDepthDefault), informationDepthCeiling: optional(values.informationDepthCeiling), promotionalStrengthDefault: optional(values.promotionalStrengthDefault), promotionalStrengthCeiling: optional(values.promotionalStrengthCeiling) }; }
function Input({ label, value, set, required = false }: { label: string; value: string; set: (value: string) => void; required?: boolean }) { return <label className="field"><span>{label}</span><input required={required} value={value} onChange={(event) => set(event.target.value)} /></label>; }
function Text({ label, value, set, required = false }: { label: string; value: string; set: (value: string) => void; required?: boolean }) { return <label className="field field-wide"><span>{label}</span><textarea required={required} value={value} onChange={(event) => set(event.target.value)} /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly string[] }) { return <label className="field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option || "none"} value={option}>{option ? option.replaceAll("_", " ") : "Use inherited / none"}</option>)}</select></label>; }
