import { getActiveWorkspace } from "@/server/active-workspace";
import { redirect } from "next/navigation";
import { ShieldCheck } from "lucide-react";
import { ApprovalActions } from "@/components/approval-actions";
import { DraftApprovalActions } from "@/components/draft-review-actions";
import { WorkspaceShell } from "@/components/workspace-shell";
import { getAuthenticatedUser } from "@/server/auth";
import { getCampaignRepository, getDraftRepository } from "@/server/database";

export default async function ApprovalsPage() { const user = await getAuthenticatedUser(); if (!user) redirect("/login"); const workspace = await getActiveWorkspace(user.id); if (!workspace) redirect("/login"); const [approvals, draftApprovals] = await Promise.all([getCampaignRepository().listApprovals(workspace.workspaceId, "pending"), getDraftRepository().listApprovals(workspace.workspaceId, "pending")]); const total = approvals.length + draftApprovals.length; return <WorkspaceShell activePath="/approvals" workspaceName={workspace.workspaceName} userName={user.displayName}><div className="resource-page"><header className="resource-header"><div><p className="eyebrow">Human control</p><h1>Approvals</h1><p>Review exact generated content and workflow inputs before downstream execution.</p></div></header><section className="resource-panel"><div className="resource-panel-head"><div><h2>Pending decisions</h2><p>{total} request{total === 1 ? "" : "s"}</p></div></div>{total === 0 ? <div className="empty-state"><span><ShieldCheck size={22} /></span><h3>No pending approvals</h3><p>Draft and workflow requests will appear here with their captured review snapshot.</p></div> : <div className="approval-queue">{draftApprovals.map((approval) => <article className="approval-request" key={approval.id}><div><span className="status-pill status-violet">content draft</span><h3>{String(approval.requestSnapshot.headline ?? "Draft approval")}</h3><p>{String(approval.requestSnapshot.campaignName ?? "")} · {String(approval.requestSnapshot.audienceName ?? "General")}</p><blockquote>{String(approval.requestSnapshot.body ?? "")}</blockquote></div><DraftApprovalActions workspaceId={workspace.workspaceId} approvalId={approval.id} /></article>)}{approvals.map((approval) => <article className="approval-request" key={approval.id}><div><span className="status-pill status-neutral">{approval.requestSnapshot.approvalScope === "campaign" ? "whole campaign" : "workflow step"}</span><h3>{String(approval.requestSnapshot.name ?? "Campaign step approval")}</h3><p>{approval.requestSnapshot.approvalScope === "campaign" ? "Approves the captured immutable campaign plan. Explicit per-step approval requirements still apply." : String(approval.requestSnapshot.desiredCapability ?? "")}</p><pre>{JSON.stringify(approval.requestSnapshot, null, 2)}</pre></div><ApprovalActions workspaceId={workspace.workspaceId} approvalId={approval.id} /></article>)}</div>}</section></div></WorkspaceShell>; }
