import { getActiveWorkspace } from "@/server/active-workspace";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Megaphone, Plus, Settings2 } from "lucide-react";
import { WorkspaceShell } from "@/components/workspace-shell";
import { getAuthenticatedUser } from "@/server/auth";
import { getCampaignRepository } from "@/server/database";

export default async function CampaignsPage() { const user = await getAuthenticatedUser(); if (!user) redirect("/login"); const workspace = await getActiveWorkspace(user.id); if (!workspace) redirect("/login"); const repository = getCampaignRepository(); const [campaigns, instances] = await Promise.all([repository.listCampaigns(workspace.workspaceId), repository.listCampaignInstances(workspace.workspaceId)]); return <WorkspaceShell activePath="/campaigns" workspaceName={workspace.workspaceName} userName={user.displayName}><div className="resource-page"><header className="resource-header"><div><p className="eyebrow">Durable orchestration</p><h1>Campaigns</h1><p>Version dependency graphs, approvals, schedules, retries, and destination handoff.</p></div><Link className="button-primary resource-button" href="/campaigns/new"><Plus size={15} />New campaign</Link></header><section className="resource-panel"><div className="resource-panel-head"><div><h2>Campaign definitions</h2><p>{instances.filter((item) => ["active", "scheduled", "paused"].includes(item.status)).length} live or queued instance{instances.length === 1 ? "" : "s"}</p></div></div>{campaigns.length === 0 ? <div className="empty-state"><span><Megaphone size={22} /></span><h3>No campaigns yet</h3><p>Create a universal workflow graph from approved packages and destinations.</p></div> : <div className="resource-table">{campaigns.map((campaign) => <article className="resource-row" key={campaign.id}><span className="resource-icon"><Megaphone size={18} /></span><div className="resource-primary"><strong>{campaign.name}</strong><p>{campaign.description || "No description"}</p></div><div><span className="resource-label">Published</span><strong>{campaign.currentVersion ? `v${campaign.currentVersion.versionNumber}` : "Not yet"}</strong></div><div><span className="resource-label">Steps</span><strong>{(campaign.draftVersion ?? campaign.currentVersion)?.steps.length ?? 0}</strong></div><span className={`status-pill ${campaign.status === "active" ? "status-green" : "status-neutral"}`}>{campaign.status}</span><Link className="icon-link" href={`/campaigns/${campaign.id}/edit`} aria-label={`Edit ${campaign.name}`}><Settings2 size={16} /></Link></article>)}</div>}</section>{instances.length > 0 && <section className="resource-panel"><div className="resource-panel-head"><div><h2>Recent workflow runs</h2><p>Temporal-backed execution state</p></div></div><div className="resource-table">{instances.slice(0, 10).map((instance) => <Link className="resource-row" href={`/campaign-instances/${instance.id}`} key={instance.id}><span className="resource-icon"><Megaphone size={18} /></span><div className="resource-primary"><strong>{campaigns.find((campaign) => campaign.id === instance.campaignId)?.name ?? "Campaign run"}</strong><p>{instance.temporalWorkflowId ?? "Awaiting dispatch"}</p></div><span className="status-pill status-neutral">{instance.status}</span></Link>)}</div></section>}</div></WorkspaceShell>; }
